"use client";
// build: v7-no-usememo
import {FormEvent,useEffect,useRef,useState} from "react";
import {ArrowDown,ArrowLeft,ArrowUp,Check,ChevronLeft,ChevronRight,Clock3,Expand,Home,ListMusic,LogOut,Maximize2,Menu,Mic2,MoreHorizontal,Music2,Search,Settings,X} from "lucide-react";
import type {Session} from "@supabase/supabase-js";
import {supabase} from "../lib/supabase";
import {initialSongs,Song} from "./data";

type Setlist={id:number;name:string;project:string;songIds:number[];updatedAt:string};
type View="home"|"songs"|"setlist"|"show";
type CloudData={songs:Song[];setlists:Setlist[]};
const initialSetlists:Setlist[]=[{id:1,name:"Clay Highway — 3 de junho 2026",project:"Banda Responsa",songIds:initialSongs.map(s=>s.id),updatedAt:"Agora"}];
const initialData:CloudData={songs:initialSongs,setlists:initialSetlists};

export default function Page(){
 const [session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false),[cloudReady,setCloudReady]=useState(false),[syncing,setSyncing]=useState(false),[syncError,setSyncError]=useState("");
 const [songs,setSongs]=useState<Song[]>(initialSongs),[setlists,setSetlists]=useState(initialSetlists),[view,setView]=useState<View>("home"),[activeId,setActiveId]=useState(1),[query,setQuery]=useState(""),[showIndex,setShowIndex]=useState(0),[saved,setSaved]=useState(true);

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);setAuthReady(true);if(!s)setCloudReady(false)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return;let cancelled=false;(async()=>{setCloudReady(false);setSyncError("");const {data,error}=await supabase.from("app_state").select("data").eq("user_id",session.user.id).maybeSingle();if(cancelled)return;if(error){setSyncError(error.message);return}if(data?.data?.songs?.length){setSongs(data.data.songs);setSetlists(data.data.setlists)}else{const {error:insertError}=await supabase.from("app_state").upsert({user_id:session.user.id,data:initialData,updated_at:new Date().toISOString()});if(insertError)setSyncError(insertError.message)}setCloudReady(true)})();return()=>{cancelled=true}},[session]);
 useEffect(()=>{if(!session||!cloudReady)return;setSaved(false);setSyncing(true);const timer=setTimeout(async()=>{const {error}=await supabase.from("app_state").upsert({user_id:session.user.id,data:{songs,setlists},updated_at:new Date().toISOString()});if(error){setSyncError(error.message);setSaved(false)}else{setSyncError("");setSaved(true)}setSyncing(false)},650);return()=>clearTimeout(timer)},[songs,setlists,session,cloudReady]);

 if(!authReady)return <Loading text="Abrindo o 21 Setlist..."/>;
 if(!session)return <AuthScreen/>;
 if(!cloudReady&&!syncError)return <Loading text="Sincronizando seu repertório..."/>;

 const active=setlists.find(s=>s.id===activeId)||setlists[0];
 const activeSongs=active.songIds.map(id=>songs.find(s=>s.id===id)).filter(Boolean) as Song[];
 const filtered=songs.filter(s=>`${s.title} ${s.artist}`.toLowerCase().includes(query.toLowerCase()));
 const move=(i:number,d:-1|1)=>{const t=i+d;if(t<0||t>=active.songIds.length)return;const ids=[...active.songIds];[ids[i],ids[t]]=[ids[t],ids[i]];setSetlists(x=>x.map(r=>r.id===active.id?{...r,songIds:ids,updatedAt:"Agora"}:r))};
 const openShow=(i=0)=>{setShowIndex(i);setView("show")};
 const nav=[{l:"Início",I:Home,a:()=>setView("home")},{l:"Repertórios",I:ListMusic,a:()=>setView("home")},{l:"Músicas",I:Music2,a:()=>setView("songs")},{l:"Configurações",I:Settings,a:()=>{}}];
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">21</div><div><strong>SETLIST</strong><span>para músicos</span></div></div><nav>{nav.map(n=><button key={n.l} onClick={n.a} className={(view==="home"&&n.l==="Início")||(view==="songs"&&n.l==="Músicas")?"active":""}><n.I size={19}/>{n.l}</button>)}</nav><div className="user-card"><div className="avatar">CS</div><div><strong>Cleto Stopa</strong><span>{session.user.email}</span></div><button className="logout-button" onClick={()=>supabase.auth.signOut()} title="Sair"><LogOut size={18}/></button></div></aside><section className="content"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">21</div><strong>SETLIST</strong></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar músicas..."/></div><button className="icon-button"><Menu/></button></header>
 {syncError&&<div className="sync-error">Erro ao sincronizar: {syncError}</div>}
 {view==="home"&&<div className="page"><div className="hero-row"><div><span className="eyebrow">PAINEL PRINCIPAL</span><h1>Boa noite, Cleto.</h1><p>Seu repertório está sincronizado na nuvem.</p></div></div><div className="stats-grid"><Stat l="Repertórios" v={String(setlists.length)} I={ListMusic}/><Stat l="Músicas salvas" v={String(songs.length)} I={Music2}/><Stat l="Com letra/cifra" v={String(songs.filter(s=>s.lyrics.length).length)} I={Mic2}/></div><div className="cards-grid"><button className="setlist-card" onClick={()=>{setActiveId(1);setView("setlist")}}><div className="cover"><ListMusic size={38}/><span>{activeSongs.length} músicas</span></div><div className="card-body"><span className="card-project">BANDA RESPONSA</span><h3>{active.name}</h3><div className="card-meta"><span><Clock3 size={15}/>repertório completo</span><span>{syncing?"Sincronizando...":"Salvo na nuvem"}</span></div></div></button></div></div>}
 {view==="songs"&&<div className="page"><div className="hero-row"><div><span className="eyebrow">BIBLIOTECA</span><h1>Suas músicas</h1><p>As {songs.length} músicas sincronizadas na sua conta.</p></div></div><div className="table-card">{filtered.map(s=><div className="table-row simple" key={s.id}><div className="song-title"><div className="mini-cover"><Music2 size={17}/></div><div><strong>{s.title}</strong><span>{s.artist}</span></div></div><span className="lyrics-status">{s.lyrics.length?"Letra/cifra cadastrada":"Sem letra"}</span></div>)}</div></div>}
 {view==="setlist"&&<div className="page"><button className="back" onClick={()=>setView("home")}><ArrowLeft size={17}/> Repertórios</button><div className="setlist-header"><div><span className="eyebrow">{active.project.toUpperCase()}</span><h1>{active.name}</h1><div className="setlist-meta"><span>{activeSongs.length} músicas</span><span>•</span><span className="save-state"><Check size={15}/>{syncing?"Sincronizando...":saved?"Salvo na nuvem":"Alterações pendentes"}</span></div></div><button className="primary" onClick={()=>openShow(0)}><Maximize2 size={17}/> Tela cheia</button></div><div className="setlist-table"><div className="setlist-row setlist-row-head"><span>#</span><span>Música</span><span>Letra</span><span>Ordem</span><span></span></div>{activeSongs.map((s,i)=><div className="setlist-row" key={s.id}><span className="position">{String(i+1).padStart(2,"0")}</span><div className="song-title"><div className="mini-cover"><Music2 size={17}/></div><div><strong>{s.title}</strong><span>{s.artist}</span></div></div><span className={s.lyrics.length?"has-lyrics":"no-lyrics"}>{s.lyrics.length?"Cadastrada":"—"}</span><div className="order-buttons"><button disabled={!i} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button disabled={i===activeSongs.length-1} onClick={()=>move(i,1)}><ArrowDown size={16}/></button></div><button className="open-song" onClick={()=>openShow(i)} title="Abrir em tela cheia"><Expand size={17}/></button></div>)}</div></div>}
 {view==="show"&&<Show songs={activeSongs} index={showIndex} setIndex={setShowIndex} exit={()=>setView("setlist")}/>}</section></main>
}

function AuthScreen(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState<"login"|"signup">("login"),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setMessage("");const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)setMessage(result.error.message);else if(mode==="signup"&&!result.data.session)setMessage("Conta criada. Confirme o e-mail e depois entre.");setLoading(false)};return <main className="auth-page"><form className="auth-card" onSubmit={submit}><div className="brand auth-brand"><div className="brand-mark">21</div><div><strong>SETLIST</strong><span>seu repertório na nuvem</span></div></div><h1>{mode==="login"?"Entrar":"Criar sua conta"}</h1><p>Use a mesma conta no computador e no celular.</p><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="seuemail@exemplo.com"/></label><label>Senha<input type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo de 6 caracteres"/></label>{message&&<div className="auth-message">{message}</div>}<button className="primary auth-submit" disabled={loading}>{loading?"Aguarde...":mode==="login"?"Entrar":"Criar conta"}</button><button type="button" className="auth-switch" onClick={()=>{setMode(mode==="login"?"signup":"login");setMessage("")}}>{mode==="login"?"Ainda não tenho conta":"Já tenho uma conta"}</button></form></main>}
function Loading({text}:{text:string}){return <main className="auth-page"><div className="loading-card"><div className="brand-mark">21</div><strong>{text}</strong></div></main>}
function Stat({l,v,I}:{l:string;v:string;I:any}){return <div className="stat"><div className="stat-icon"><I size={21}/></div><div><strong>{v}</strong><span>{l}</span></div></div>}
function Show({songs,index,setIndex,exit}:{songs:Song[];index:number;setIndex:(n:number)=>void;exit:()=>void}){const start=useRef(0);const s=songs[index];useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.key==="ArrowRight")setIndex(Math.min(songs.length-1,index+1));if(e.key==="ArrowLeft")setIndex(Math.max(0,index-1));if(e.key==="Escape")exit()};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[index,songs.length,setIndex,exit]);if(!s)return null;const go=(d:number)=>setIndex(Math.max(0,Math.min(songs.length-1,index+d)));const next=songs[index+1];const short=(title:string)=>title.length>18?`${title.slice(0,18).trim()}…`:title;return <div className="lyrics-full" onTouchStart={e=>start.current=e.touches[0].clientX} onTouchEnd={e=>{const dx=e.changedTouches[0].clientX-start.current;if(Math.abs(dx)>55)go(dx<0?1:-1)}}><button className="floating-exit" onClick={exit}><X/></button><button className="swipe-side left" disabled={index===0} onClick={()=>go(-1)}><ChevronLeft/></button><button className="swipe-side right" disabled={index===songs.length-1} onClick={()=>go(1)}><ChevronRight/></button><header className="lyrics-head"><div><span>{String(index+1).padStart(2,"0")} / {songs.length}</span><h1>{s.title}</h1><p>{s.artist}</p></div><div className="swipe-hint">Arraste para o lado</div></header><section className="lyrics-sheet" style={{"--line-count":Math.max(s.lyrics.length,1)} as React.CSSProperties}>{s.lyrics.length?s.lyrics.map((l,i)=><div key={i} className="lyric-line" style={{background:l.bg||"transparent",fontWeight:l.bold?800:500,fontStyle:l.italic?"italic":"normal"}}>{l.text}</div>):<div className="empty-lyrics">Letra ainda não cadastrada para esta música.</div>}</section><footer className="lyrics-footer"><button disabled={index===0} onClick={()=>go(-1)}><ArrowLeft/> Anterior</button><strong>{next?.title||"Fim do repertório"}</strong><button className="next-button" disabled={!next} onClick={()=>go(1)}><span>Próxima<small>{next?short(next.title):"Fim"}</small></span><ChevronRight/></button></footer></div>}
